import Foundation

class CafeDialogue {
    var round1Question1 = "Hi, what can I get you?"
    var round1Question1Response1 = "Do you have any specials?"
    var round1Question1Response2 = "Just a sec."
    var round1Question1Response3 = "What coffees do you have?"
    
    var round2Question1 = "Our soup of the day is minestr-oh-no."
    var round2Question1Response1 = "Oh, I'm actually looking for coffee!"
    var round2Question1Response2 = "Oh, that's not what I want."
    var round2Question1Response3 = "I'll get that!"
    
    var round2Question2 = "Hey! There are other customers waiting."
    var round2Question2Response4 = "I know. I'm sorry. What coffees do you have?"
    var round2Question2Response5 = "Just give me a second."
    var round2Question2Response6 = "What's your problem?"
    
    var round2Question3 = "We have the Brewster's Blend, the Java Jolt, the Roast Riddle, and the Morning Mist."
    var round2Question3Response7 = "What's a Java Jolt?"
    var round2Question3Response8 = "What's a Roast Riddle?"
    var round2Question3Response9 = "What's a Brewster's Blend?"
    
    var round3Question1 = "No problem. Our coffees are $4 for a medium and $5 for large."
    var round3Question1Response1 = "A medium Brewster's Blend please."
    var round3Question1Response2 = "A large Java Jolt please."
    var round3Question1Response3 = "A large Roast Riddle please."
    
    var round3Question2 = "Did you want a coffee instead?"
    var round3Question2Response4 = "Yes please. The largest latte I can get for $4.50, please."
    var round3Question2Response5 = "Yes! A large cappuccino please."
    var round3Question2Response6 = "No, don't worry about it."
    
    var round3Question3 = "Great. $8.80 please."
    var round3Question3Response7 = "Oh, sorry, I want coffee instead."
    var round3Question3Response8 = "Here you are."
    var round3Question3Response9 = "Actually, don't worry..."
    
    var round3Question4 = "We have the Brewster's Blend, the Java Jolt, the Roast Riddle, and the Morning Mist."
    var round3Question4Response10 = "A medium Brewster's Blend please."
    var round3Question4Response11 = "A large Java Jolt please."
    var round3Question4Response12 = "A large Roast Riddle please."
    
    var round3Question5 = "Be quick!"
    var round3Question5Response13 = "A medium Brewster's Blend please."
    var round3Question5Response14 = "A large Java Jolt please."
    var round3Question5Response15 = "A large Roast Riddle please."
    
    var round3Question6 = "Excuse me?"
    var round3Question6Response16 = "I'm really sorry. A medium Brewster's Blend please."
    var round3Question6Response17 = "Sorry. A large Java Jolt please."
    var round3Question6Response18 = "Stuff you, buddy!"
    
    var round3Question7 = "A cappuccino."
    var round3Question7Response19 = "A large Java Jolt please!"
    var round3Question7Response20 = "A medium Java Jolt please!"
    var round3Question7Response21 = "Can I please have the latte?"
    
    var round3Question8 = "Our special take on a flat white."
    var round3Question8Response22 = "A medium Roast Riddle please."
    var round3Question8Response23 = "A large Roast Riddle please."
    var round3Question8Response24 = "I'd like the latte."
    
    var round3Question9 = "Our version of a latte!"
    var round3Question9Response25 = "I'll have that in a medium, please."
    var round3Question9Response26 = "I'll grab a large Brewster's Blend."
    var round3Question9Response27 = "Can I have a large Roast Riddle please?"
    
    var round4Question1 = "Coming right up. $4 please."
    var round4Question2 = "Coming right up. $5 please."
    var round4Question3 = "Coming right up. $5 please."
    var round4Question4 = "Great! That's a Brewster's Blend in a medium. $4 please."
    var round4Question5 = "Coming right up. $5 please."
    var round4Question6 = "No problem. Have a nice day."
    var round4Question7 = "No problem. What coffee can I get you?"
    var round4Question8 = "Thanks! It'll be out soon."
    var round4Question9 = "No problem. Have a nice day."
    var round4Question10 = "Coming right up. $4 please."
    var round4Question11 = "Coming right up. $5 please."
    var round4Question12 = "Coming right up. $5 please."
    var round4Question13 = "Coming right up. $4 please."
    var round4Question14 = "Coming right up. $5 please."
    var round4Question15 = "Coming right up. $5 please."
    var round4Question16 = "That's $4."
    var round4Question17 = "That's $5."
    var round4Question18 = "Get out of my cafe!"
    var round4Question19 = "Coming right up. $5 please."
    var round4Question20 = "Coming right up. $4 please."
    var round4Question21 = "Coming right up. $4 please."
    var round4Question22 = "Coming right up. $4 please."
    var round4Question23 = "Coming right up. $5 please."
    var round4Question24 = "Coming right up. $4 please."
    var round4Question25 = "Sure. $4 please."
    var round4Question26 = "Coming right up. $5 please."
    var round4Question27 = "Coming right up. $5 please."
}
